name: PureKitPvP
version: '${project.version}'
main: me.lifelessnerd.purekitpvp.PureKitPvP
api-version: 1.19
authors: [ LifelessNerd, PsionicPvP ]
description: KitPVP plugin, with kit functionality from PureKits (abandoned)
commands:
  getkit:
    description: Gives you a kit.
    usage: /getkit <kitName>
  kit:
    description: Shows kit selection GUI.
    usage: /kit
  suicide:
    description: Kill yourself in pvp.
    usage: /suicide
  getstats:
    description: Get the stats of a player.
    usage: /getstats <player>
    aliases:
      - stats
      - pvpstats
  purekitpvp:
    description: All admin commands. See documentation for help.
    usage: /purekitpvp <createkit/deletekit/kitstats/setkillitem/setperk/getcustomitem/createloottable/reload>
    aliases:
      - kitpvp
      - pkpvp
  purekitpvphelp:
    description: Get PureKitPvP help, for the common folk
    usage: /purekitpvphelp
    aliases:
      - pkpvphelp
      - pvphelp
  perk:
    description: Perk menu
    usage: /perk a



